apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g8gi134xo-go 
  janus-idp.io/tekton: g8gi134xo-go
  backstage.io/kubernetes-id: g8gi134xo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g8gi134xo-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml